version: '3'
services:
  #  Imagem Oficial do rabbit
  rabbit:
    image: rabbitmq:3.7-management-alpine
    environment: 
      RABBITMQ_DEFAULT_USER: adm_user
      RABBITMQ_DEFAULT_PASS: mudar12345
    ports:
       - 15672:15672 
       - 5672:5672
    networks: 
      - services    
  # Api1
  api1:
    build: 
      context: ./src
      dockerfile: Dockerfile-api1 
    depends_on:
      - rabbit
    ports:
      - 3001:80
    networks: 
      - services      
  # Api2
  api2:
    build: 
      context: ./src
      dockerfile: Dockerfile-api2
    depends_on:
      - rabbit
    ports:
      - 3002:80 
    networks: 
      - services   

networks:
  services:
