version: '3.7'
services:  
  # Api1
  api1:
    build: 
      context: ./
      dockerfile: Dockerfile-api1 
    ports:
      - 3001:80
    networks: 
      - services
    links: 
      - rabbit 
    depends_on:
      - rabbit     
  # Api2
  api2:
    build: 
      context: ./
      dockerfile: Dockerfile-api2    
    ports:
      - 3002:80 
    networks: 
      - services
    links: 
      - rabbit
    depends_on:
      - rabbit
  #  Imagem Oficial do rabbit
  rabbit:
    image: rabbitmq:3.7-management-alpine
    environment: 
      RABBITMQ_DEFAULT_USER: adm_user
      RABBITMQ_DEFAULT_PASS: mudar12345
    ports:
       - 15672:15672 
       - 5672:5672
    networks: 
      - services
networks:
  services:
