FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine3.11 as build

WORKDIR /app

COPY . ./

RUN dotnet restore Micro2/Micro2.csproj

RUN dotnet build Micro2/Micro2.csproj -c Release

RUN dotnet publish  Micro2/Micro2.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine3.11

WORKDIR /app
# Copia os arquivos publicados do container de build para o container final
COPY --from=build /app/out .
# Define qual o executavel do container
ENTRYPOINT [ "dotnet","Micro2.dll"]

