FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine3.11 as build

WORKDIR /app

COPY . ./

RUN dotnet restore Micro1/Micro1.csproj

RUN dotnet build Micro1/Micro1.csproj -c Release

RUN dotnet publish  Micro1/Micro1.csproj -c Release -o out

CMD ls

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine3.11

WORKDIR /app
# Copia os arquivos publicados do container de build para o container final
COPY --from=build /app/out .
# Define qual o executavel do container
ENTRYPOINT [ "dotnet","Micro1.dll"]

